### ISSUE TITLE
Servers\<name>\Rocket not downloading

### ISSUE THREAD

**Issue by NewbieHookTheWebhook** [RocketMod/Rocket#1155] opened 2019-10-23 05:21 UTC
**What problem did you notice?**
Servers\<name>\Rocket not downloading
**What is the expected result?**
I expected it to download, but it didn't.
**What is the current result?**
Servers\Server1\Rocket is not valid.
**How to reproduce the issue?**
There is no way, unless I try again.

**Comment by Trojaner** [comment] 2019-10-23 14:54
Closing since the issue is invalid

**Closed by Trojaner** 2019-10-23 14:54 UTC
