### ISSUE TITLE
can somebody help me with this error

### ISSUE THREAD

**Issue by DracolyteHD** [RocketMod/Rocket#953] opened 2017-07-17 12:27 UTC
Rocket.CoreException in Rocket.Core: System.Exception: Failed to deserialize XMLFileAsset: Permissions.config.xml ---> System.Xml.XmlException: 'Members' is expected  Line 58, position 8.
  at Mono.Xml2.XmlTextReader.Expect (System.String expected) [0x00000] in <filename unknown>:0
  at Mono.Xml2.XmlTextReader.ReadEndTag () [0x00000] in <filename unknown>:0
  at Mono.Xml2.XmlTextReader.ReadContent () [0x00000] in <filename unknown>:0
  at Mono.Xml2.XmlTextReader.ReadContent () [0x00000] in <filename unknown>:0
  at Mono.Xml2.XmlTextReader.Read () [0x00000] in <filename unknown>:0
  at System.Xml.XmlTextReader.Read () [0x00000] in <filename unknown>:0
  at System.Xml.XmlDocument.ReadNodeCore (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Xml.XmlDocument.ReadNode (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReader.ReadXmlNode (Boolean wrapped) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReader.UnknownNode (System.Object o, System.String qnames) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReader.UnknownNode (System.Object o) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadListElement (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, System.Object list, Boolean canCreateInstance) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers (System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObjectElement (System.Xml.Serialization.XmlTypeMapElementInfo elem) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadListElement (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, System.Object list, Boolean canCreateInstance) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadMembers (System.Xml.Serialization.ClassMap map, System.Object ob, Boolean isValueList, Boolean readByOrder) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstanceMembers (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadClassInstance (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadObject (System.Xml.Serialization.XmlTypeMapping typeMap, Boolean isNullable, Boolean checkType) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot (System.Xml.Serialization.XmlTypeMapping rootMap) [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializationReaderInterpreter.ReadRoot () [0x00000] in <filename unknown>:0
  at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.Serialization.XmlSerializationReader reader) [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at Rocket.Core.Assets.XMLFileAsset`1[Rocket.API.Serialisation.RocketPermissions].Load (Rocket.API.AssetLoaded`1 callback) [0x00000] in <filename unknown>:0
  at Rocket.Core.Assets.XMLFileAsset`1[Rocket.API.Serialisation.RocketPermissions]..ctor (System.String file, System.Type[] extraTypes, Rocket.API.Serialisation.RocketPermissions defaultInstance) [0x00000] in <filename unknown>:0
  at Rocket.Core.Permissions.RocketPermissionsManager.Start () [0x00000] in <filename unknown>:0

**Comment by DracolyteHD** [comment] 2017-07-17 12:30
hastebin link to my Permissions.config.xml

**Comment by persiafighter** [comment] 2017-07-17 12:48
Issue not following the format. Please reopen this using the correct format that comes available when creating an issue. @Trojaner25 close this.

**Comment by Trojaner25** [comment] 2017-07-17 12:49
Beside that, your Permissions.config.xml is broken. This is not a bug.

**Closed** 2017-07-17 12:48 UTC

**Comment by DracolyteHD** [comment] 2017-07-17 15:20
so i cant do anything more?

**Comment by persiafighter** [comment] 2017-07-17 15:23
You can fix your permissions file, instead of creating an issue that is not a programming error, rather a user error. Also, if you need it, http://www.xmlvalidation.com/ use it to check if you finally were able to fix your perms file in terms of structure.
