### ISSUE TITLE
Permission inheritance is broken

### ISSUE THREAD

**Issue by CSYUnturned** [RocketMod/Rocket#928] opened 2017-05-30 10:23 UTC
Just encounted a problem with the latest version

When a plugin has non wild card permissions, eg kit.blah or vault.blah (I have different kits and vaults for different permission levels) any permissions in the permission file with a "." eg kit.amry give the error of no permission to a player, myself as owner / admin can use it.
My arena server was fine as that has kits but with kit.* so it allowed everybody to still use it.

I downloaded version 1200 again and replaced version 1202 and everything started working again.

Thanks
Matt

**Comment by Trojaner25** [comment] 2017-05-30 22:41
Probably caused by #925

**Comment by Trojaner25** [comment] 2017-05-30 22:42
Did you also add "kit" permission?
You need "kit" and "kit.*"

**Comment by CSYUnturned** [comment] 2017-05-31 01:14
Ok, I'll give that a go, I didn't have the kit permission, just the following example
        <Permission Cooldown="0">kits</Permission>
        <Permission Cooldown="0">kit.JohnWick</Permission>
        <Permission Cooldown="0">kit.Jason</Permission>
        <Permission Cooldown="0">kit.Rambo</Permission>

I'm assuming added <Permission Cooldown="0">kit</Permission> this wont give them full access to all kits and the same goes for the vault permission?

I don't have the wildcard kit.* as vip and vipplus members get extra kits and larger vaults.

This hasn't been a problem in the past and broke with the latest version for some reason.

Thanks for your response, I'll let you know how I get on

Matt

**Comment by CSYUnturned** [comment] 2017-06-01 02:35
Trojaner,

Just confirming this was the issue, I added the permission>kit< and >vault< which doesn't give wildcard access but allows the individual controls after that to work

Thanks for your assistance
Matt

**Comment by fr34kyn01535** [comment] 2018-03-28 22:34
Wontfix. Consider in #1007

**Closed by fr34kyn01535** 2018-03-28 22:34 UTC
Labels: bug
