### ISSUE TITLE
Rocket for Linux build 759 just quits

### ISSUE THREAD

**Issue by unturnedplayer** [RocketMod/Rocket#861] opened 2016-11-12 00:38 UTC
After updating to the latest Linux 759 build, Rocket just quits after registering the last command (which is /vanish) and printing out the next line indicating the server will save every x seconds.  There are no error messages; it just quits.  This was tested with no plugins installed and same problem occurred on the previous 757 build.

**Comment by snowball7275** [comment] 2016-11-12 01:53
I had the same issue, installed mono-complete, and now I'm getting this error:

Error while compiling generated serializer
(0,0) : error CS0006: Metadata file `/root/data-0xa96eb80' could not be found

**Comment by unturnedplayer** [comment] 2016-11-12 02:07
I get the same error your getting but I don't think that affects Rocket as it appears randomly during loading the server.  I think the problem is BattlEye cause I looked at the Logs.txt file and it shows the following error:

3.17.5.1

Unhandled exception when BattlEye server library!

**Comment by unturnedplayer** [comment] 2016-11-12 02:12
Ok. It's confirmed that BattlEye is causing this problem on Linux servers.  If BattlEye is disabled in the Config.json file then my server loads fine.  The fix would be if there is an equivalent Unturned_BE.exe binary for Linux.

**Comment by snowball7275** [comment] 2016-11-12 02:27
Yep, just loaded up the server and it works just peachy without BattlEye.

**Comment by KEJustusKE** [comment] 2016-11-12 08:19
Does anyone now if they make the feature for linux too?

**Comment by snowball7275** [comment] 2016-11-12 11:59
BattlEye? Yes, that's for linux as well. To fix the issue, just disable BattlEye in the config.json file in the instance folder.

**Comment by unturnedplayer** [comment] 2016-11-12 12:50
He was asking about whether the BattlEye binary is available for Linux, not how to disable it.

**Comment by KEJustusKE** [comment] 2016-11-12 13:08
Yeah right because at the moment BattlEye is really useless, if I run my servers over linux. xD

**Comment by snowball7275** [comment] 2016-11-12 13:25
Ah. Ignore my comment, then. Yes, BattlEye is for Linux as well, but we have just found out that in order for the unturned server to load, for now, you have to disable it.

**Comment by snowball7275** [comment] 2016-11-13 00:19
Anyone checked whether the issue is fixed with build 960?

**Comment by unturnedplayer** [comment] 2016-11-13 01:30
I'm assuming you meant 760.  No not fixed.  It's not an issue with Rocket as far as I can tell as there needs to be a Linux version of the BattlEye binary.

**Closed** 2016-11-13 01:31 UTC
